### ISSUE TITLE
Update graphql peer dependency range

### ISSUE THREAD

**Issue by Akryum** [apollographql/apollo-link-persisted-queries#16]
Currently, the `graphql` peer dependency [is fixed](https://github.com/apollographql/apollo-link-persisted-queries/blob/master/package.json#L48) at `0.11.7`, which causes some warnings when our users install [@vue/cli](https://github.com/vuejs/vue-cli). Is there a reason for this? Shouldn't it be updated?

**Comment by glasser** [comment]
Thanks!
