### ISSUE TITLE
Status code for PersistedQueryNotFound

### ISSUE THREAD

**Issue by Daniel15** [apollographql/apollo-link-persisted-queries#35]
The readme says:

> Error Responses When the initial query signature is received by a backend, if it is unable to find the hash previously stored, it must send back the following response signature:
> ```
> {
>  errors: [
>    { message: 'PersistedQueryNotFound' }
>  ]
> }
> ```

What should the HTTP response code be? Should it still be 200 OK, or should it be something else?

**Comment by SirensOfTitan** [comment]
@Daniel15: Seems like it should be 200 https://github.com/apollographql/apollo-server/blob/ceee5db460f002a80b837ff0dba1743d4237aaf0/packages/apollo-server-integration-testsuite/src/index.ts#L476

... although this comment here makes it superficially unclear: https://github.com/apollographql/apollo-link-persisted-queries/blob/master/src/index.ts#L48
