### ISSUE TITLE
Possible to combine with apollo-link-batch-http?

### ISSUE THREAD

**Issue by kamsar** [apollographql/apollo-link-persisted-queries#8]
Is there a way to combine automatic persisted queries with a [batched link](https://www.apollographql.com/docs/link/links/batch-http.html)? Guessing not yet, at least it didn't work if I replaced the concat to the HTTP link with a batched instance, but thought I'd ask.

Great idea, really reduces bandwidth :)

Edit: to be more detailed, this is how I tried to combine them:

```
import { BatchHttpLink } from 'apollo-link-batch-http';
import { createPersistedQueryLink } from 'apollo-link-persisted-queries';

const http = new BatchHttpLink({ uri: httpEndpointUrl });
const persistHttp = createPersistedQueryLink().concat(http);
```

It does send the queries, but the negotiation of hashes doesn't happen so there is no bandwidth savings. The batch elements have both the complete query text as well as the hash extension added to them.

**Comment by wmertens** [comment]
I wonder if https://github.com/apollographql/apollo-link/pull/364 will make it work with batching. I'm going to guess "no" :)

**Comment by kamsar** [comment]
@wmertens I suspect that it will, because on further reflection I think the reason it doesn't work with `BatchHttpLink` today is that it is using `apollo-fetch` which may have a different internal API (speculating here) than the plain old HTTP link. It definitely works a lot different if you want to pass credentials with requests.

**Comment by kamsar** [comment]
As of `apollo-link-batch-http`  1.2, this now just works, because apollo-fetch is no longer a dependency of the batcher. Thanks @evans :)
